In [0]:
import pandas as pd
import numpy as np

from sklearn.dummy import DummyRegressor
from sklearn.tree import DecisionTreeRegressor

from sklearn.metrics import mean_absolute_error as mae
from sklearn.model_selection import cross_val_score

import eli5
from eli5.sklearn import PermutationImportance


In [9]:
!pip install --upgrade tables

     |████████████████████████████████| 4.3MB 2.7MB/s 
  Found existing installation: tables 3.4.4
    Uninstalling tables-3.4.4:
      Successfully uninstalled tables-3.4.4


In [10]:
!pip install eli5

     |████████████████████████████████| 112kB 2.8MB/s 


In [42]:
cd /content/drive/My Drive/Cloab Notebooks/matrix/matrix_two/dw_matrix_car/

/content/drive/My Drive/Cloab Notebooks/matrix/matrix_two/dw_matrix_car


In [43]:
df = pd.read_hdf('data/car.h5')
df.shape

(106494, 155)

In [16]:
df.columns

Index(['breadcrumb', 'created_at', 'price_currency', 'price_details',
       'price_value', 'seller_address', 'seller_name', 'seller_type',
       'feature_czujniki-parkowania-przednie',
       'feature_poduszka-powietrzna-chroniąca-kolana',
       ...
       'param_pearl', 'param_stan', 'param_wersja', 'param_emisja-co2',
       'param_body-type', 'param_matowy', 'param_bezwypadkowy',
       'param_akryl-(niemetalizowany)', 'param_monthly-payment-value',
       'car_id'],
      dtype='object', length=155)

In [17]:
df.select_dtypes(np.number).columns

Index(['price_value', 'car_id'], dtype='object')

In [25]:
# Uproszczona Wersja
# feats = ['car_id']
# X = df [feats].values

X=df[ ['car_id']].values
y=df[ 'car_id'].values

model = DummyRegressor()
model.fit(X,y)
y_pred = model.predict(X)

mae(y, y_pred)



40104.125306754606

In [26]:
  [ x for x in df.columns if 'price' in x]


['price_currency', 'price_details', 'price_value']

In [27]:
df['price_currency'].value_counts()

PLN    106290
EUR       204
Name: price_currency, dtype: int64

In [28]:
  df['price_currency'].value_counts(normalize=True) * 100

PLN    99.80844
EUR     0.19156
Name: price_currency, dtype: float64

In [32]:
df['price_currency'].value_counts()

PLN    106290
Name: price_currency, dtype: int64

In [33]:
df = df[ df['price_currency'] != 'EUR']
df.shape

(106290, 155)

FEATURE ENGENERING

In [34]:
df.head()

breadcrumb  ... car_id
0    [Osobowe, Dacia, Logan, Dacia Logan II (2012-)]  ...      0
2  [Osobowe, Peugeot, 3008, Peugeot 3008 I (2009-...  ...      2
3  [Osobowe, Porsche, Cayenne, Porsche Cayenne II...  ...      3
4  [Osobowe, Peugeot, 308, Peugeot 308 T7 (2008-2...  ...      4
5  [Osobowe, Volkswagen, Golf, Volkswagen Golf VI...  ...      5

[5 rows x 155 columns]

In [35]:
df['param_color'].factorize()

(array([-1, -1, -1, ..., -1, -1, -1]),
 Index(['Czarny', 'Srebrny', 'Złoty', 'Bordowy', 'Biały', 'Szary', 'Beżowy',
        'Zielony', 'Fioletowy', 'Niebieski', 'Inny kolor', 'Brązowy', 'Żółty'],
       dtype='object'))

In [38]:
df['param_color'].factorize()

(array([-1, -1, -1, ..., -1, -1, -1]),
 Index(['Czarny', 'Srebrny', 'Złoty', 'Bordowy', 'Biały', 'Szary', 'Beżowy',
        'Zielony', 'Fioletowy', 'Niebieski', 'Inny kolor', 'Brązowy', 'Żółty'],
       dtype='object'))

In [40]:
df['param_color'].factorize()[0]

array([-1, -1, -1, ..., -1, -1, -1])

In [0]:
SUFFIX_CAT  = '__cat'
for feat in df.columns:
  if isinstance(df[feat][0], list): continue
  
  factorize_values = df[feat].factorize()[0]
  if SUFFIX_CAT in feat: 
   df[feat] = factorize_values
  else:
   df[feat + SUFFIX_CAT] = factorize_values

# Rozwinięcie:
# 1 Iteracja pętli
#'a'
#'a__cat'
# 2 Iteracja
#'a'
#'a__cat'
#'a_cat__cat'
# Tutaj w drugiej Iteracji pojawi się jeszcze raz __cata - Nie chcemy tego tak mieć. 


In [46]:
cat_feats = [ x for x in df.columns if SUFFIX_CAT in x ]
cat_feats = [x for x in cat_feats if 'price' not in x]
len(cat_feats)

151

In [48]:
X = df[cat_feats].values
y = df['price_value'].values


model = DecisionTreeRegressor(max_depth=5)
scores = cross_val_score(model, X,y, cv=3, scoring='neg_mean_absolute_error' )
np.mean(scores)

-19695.13091100928

Sprawdzanie Cech - które są Ciekawe



In [51]:
m = DecisionTreeRegressor(max_depth=5)
m.fit(X,y)

imp = PermutationImportance (m, random_state=0).fit(X,y)
eli5.show_weights(imp, feature_names=cat_feats)

In [53]:
cd /content/drive/My Drive/Cloab Notebooks/matrix/matrix_two/dw_matrix_car/

/content/drive/My Drive/Cloab Notebooks/matrix/matrix_two/dw_matrix_car


In [59]:
ls

data/            day2_visualization.ipynb  LICENSE
Day1_meta.ipynb  Day3_Model.ipynb          README.md


Trzeba potem przenieść pliki z dysku Google do powyższej ścieżki


In [0]:
!git config --global user.email "smachnio@wp.pl"
!git config --global user.name "Sylwek"

DODANIE ZMIAN DO GITHUBA


In [0]:
!git add Day3_model.ipynb
!git add Day1_meta.ipynb
!git commit -m "add model"

In [61]:
!git push -u origin master

Counting objects: 3, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 944 bytes | 78.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/smachnio/dw_matrix_car.git
   6a9c1d5..532bc99  master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.
